[tool.poetry]
name = "poetry-env"
version = "0.1.0"
description = ""
authors = ["Omar Bouattour <omar.bouattour@yahoo.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
